### ISSUE TITLE
Error on malware.yara

### ISSUE THREAD

**Issue by petikvx** [ditekshen/detection#11]
`petikvx-ressources/yara/malware.yar(4119): error: syntax error, unexpected identifier, expecting '('
`

**Comment by ditekshen** [comment]
No errors on local tests and yara-ci. Check your yara version.

https://github.com/ditekshen/detection/blob/2ce6878bd7e3f1614c2d21fd7b38c76bd3a4995e/yara/malware.yar#L4103

**Comment by petikvx** [comment]
Yara updated and good working
