### ISSUE TITLE
Possible typo in MALWARE_Linux_RansomExx

### ISSUE THREAD

**Issue by PeterMatula** [ditekshen/detection#17]
I was randomly browsing your malware rules when my eyes landed on `MALWARE_Linux_RansomExx` [condition](https://github.com/ditekshen/detection/blob/e6579590779f62cbe7f5e14b5be7d77b2280f516/yara/malware.yar#L3857C36-L3857C44). It says `5 of ($s*) or 6 of ($s*)` which does not make sense to me. From the context I would guess it should be something like: `5 of ($s*) or 6 of ($c*)`. I would make a PR, but I'm not really sure if I'm guessing right.

**Comment by ditekshen** [comment]
Thanks! It should have been ```5 of ($c*) or 6 of ($s*)```. Its fixed in https://github.com/ditekshen/detection/commit/0519f0af59045d5a7e1049f416903e9db2da2c8a.
