### ISSUE TITLE
Error on ditekSHen.INDICATOR.Win.RMM.SplashtopStreamer

### ISSUE THREAD

**Issue by teoberi** [ditekshen/detection#19]
Testing database: '/clamav/tmp.832b29def2/clamav-fb303f0944c421493aec366ccf3ea20f.tmp-indicator_rmm.ldb' ...
WARNING: [LibClamAV] cli_add_content_match_pattern: Problem adding signature (3).
WARNING: [LibClamAV] cli_loadldb: failed to parse subsignature 0 in ditekSHen.INDICATOR.Win.RMM.SplashtopStreamer
WARNING: [LibClamAV] Problem parsing database at line 12
WARNING: [LibClamAV] Can't load /clamav/tmp.832b29def2/clamav-fb303f0944c421493aec366ccf3ea20f.tmp-indicator_rmm.ldb: Malformed database
ERROR: Failed to load new database: Malformed database
WARNING: Database load exited with "Test failed"
ERROR: Database test FAILED.
Unexpected error when attempting to update from custom database URL: https://raw.githubusercontent.com/ditekshen/detection/master/clamav/indicator_rmm.ldb
WARNING: fc_download_url_databases: fc_download_url_database failed: Test failed (8)
ERROR: Database update process failed: Test failed
ERROR: Update failed.

**Comment by ditekshen** [comment]
Thanks! Fixed in https://github.com/ditekshen/detection/commit/8a781cd417b14b96e03dd150f955196b74523674.
