### ISSUE TITLE
There no problems at Linux but I have problems on Windows

### ISSUE THREAD

**Issue by HydraDragonAntivirus** [ditekshen/detection#20]
Invalid file name pe.number_of_signatures on Windows 
Error compiling YARA rule from C:\Users\victim\Desktop\Antivirus\YARA\Bartblaze.yar: C:\Users\victim\Desktop\Antivirus\YARA\Bartblaze.yar(2808): invalid field name "number_of_signatures"
Error compiling YARA rule from C:\Users\victim\Desktop\Antivirus\YARA\Blackberry_index.yar: C:\Users\victim\Desktop\Antivirus\YARA\Blackberry_index.yar(303): invalid field name "number_of_signatures"
Error compiling YARA rule from C:\Users\victim\Desktop\Antivirus\YARA\ditekshen.yar: C:\Users\victim\Desktop\Antivirus\YARA\ditekshen.yar(11623): invalid field name "number_of_signatures"
Error compiling YARA rule from C:\Users\victim\Desktop\Antivirus\YARA\ESET.yar: C:\Users\victim\Desktop\Antivirus\YARA\ESET.yar(3899): invalid field name "number_of_signatures"
How can I fix that?

**Comment by ditekshen** [comment]
None of the above rules are relevant to this repository. I do not know what's inside these files. Check your aggregation code, your Yara version, etc. 

This is the second time you submit an issue that is not relevant. To quote your own response from the previous issue:

```
From: Emirhan Uçan <notifications@github.com>
Sent: Friday, October 13, 2023 4:52 PM
To: ditekshen/detection <detection@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: Re: [ditekshen/detection] Error on Malware_Win_Warezov malware.yar (Issue #18)
 

Oops there problem in the my code sorry.
```

You can use any search engine to lookup "how to fix that".
