### ISSUE TITLE
esetonlinescanner got detected by your signatures

### ISSUE THREAD

**Issue by HydraDragonAntivirus** [ditekshen/detection#22]
![image](https://github.com/ditekshen/detection/assets/142328963/ff72928e-5386-4bd1-98f5-de2d8abb4330)

**Comment by ditekshen** [comment]
Scanning security tools with security tools? Plus, that file can be anything, no one knows if its legitimate or not, just its name is showing here.

**Comment by HydraDragonAntivirus** [comment]
That's still big false positive. If you don't believe me try yourself.

**Comment by HydraDragonAntivirus** [comment]
![image](https://github.com/ditekshen/detection/assets/142328963/3d7ccf1d-9cad-4f3b-be7d-5b5c3109c8f9)
 Also this.

**Comment by ditekshen** [comment]
No one knows what these files are, they could be malware for all I know. Feel free to PR fixes.

**Comment by HydraDragonAntivirus** [comment]
Thank you! https://www.virustotal.com/gui/file/9f6dbfa52c7a733ec39085b78809aff22703443304ef73b4597334889c22fe71/relations Here is the file of virustotal result.  
[System.ni.zip](https://github.com/ditekshen/detection/files/13464545/System.ni.zip)
