### ISSUE TITLE
INDICATOR_SUSPICIOUS_EXE_RawGitHub_URL

### ISSUE THREAD

**Issue by UnrealKaraulov** [ditekshen/detection#27]
https://www.virustotal.com/gui/file/00ad0e9044afb64c3d74e64636db472fc6cceab65eeb836fef253292f6286df8?nocache=1

I use github url for version check, and virustotal print : 
![image](https://github.com/ditekshen/detection/assets/88730285/4fa143d1-44ee-4d22-a272-cf17ccbabc02)

How to fix it?

**Comment by ditekshen** [comment]
Fixed in https://github.com/ditekshen/detection/commit/2ddbbe14eea1f342bca2cfd09a643a40ae2fcaf6.

**Comment by UnrealKaraulov** [comment]
@ditekshen 

https://github.com/UnrealKaraulov/UnrealDemoScanner/blob/5325568e9032b8171a15090e127140b54dd86b7c/UnrealDemoScanner/UnrealDemoScanner.cs#L2277

Maybe need check file content or extension (.dll/.exe/.drv/...) ?

In my case I just use it for version check.
