### ISSUE TITLE
please help me to unpack a file with ConfuserEx Mod

### ISSUE THREAD

**Issue by Siddugggggyjkygj** [ditekshen/detection#28]
please help me to unpack a file with ConfuserEx Mod https://cdn.discordapp.com/attachments/899925333959147530/1249196434071490610/unpack.zip?ex=66666c56&is=66651ad6&hm=d182728b46ec412c4555e1d2d5a8e2e52d8057a20fb26292b88fc8a2f1fe2558&

**Comment by ditekshen** [comment]
This is not what this repo is about. Sorry, but I can't help. There are plethora of resources available online for unpacking ConfuserEx.

**Comment by Siddugggggyjkygj** [comment]
can you help me to find resourses
