### ISSUE TITLE
False detection on virustotal?

### ISSUE THREAD

**Issue by semenenkov** [ditekshen/detection#4]
Hello,

I've just got this on [virustotal](https://www.virustotal.com/gui/file/cffce548908795ee799cedb47f13b3ce824b89b765b43eb09b67288de4467906):

_Matches rule INDICATOR_KB_CERT_3300000187721772155940c709000000000187 by ditekSHen from ruleset indicator_knownbad_certs at https://github.com/ditekshen/detection
**Detects executables signed with stolen, revoked or invalid certificates**_

That's the msi of [my app](https://db-merge-tools.net/sqlite-diff-merge-overview.html). At first I haven't heard that my cert is stolen or revoked and it is not invalid. The next interesting thing is that [report for executable](https://www.virustotal.com/gui/file/2fa5797625f8860f4f44609736baae70fe6db956317cabe8042479beeb6ac83f) inside that msi has no that error.

Fortunately I see this error only when I signed in to virustotal, but I am not sure how and by who these rules are applied and how this may affect end users. To me it just looks like an unfounded accusation.

**Comment by ditekshen** [comment]
Fixed in https://github.com/ditekshen/detection/commit/76863acf1564ed697a2e1eba803908c27e98cdc7

**Comment by semenenkov** [comment]
Thank you!
