### ISSUE TITLE
Akeo Consulting certificate rule

### ISSUE THREAD

**Issue by pbatard** [ditekshen/detection#5]
Hi,

I'm the developer behind Akeo Consulting, and I am very surprised to see the credentials I use to sign my software in your list of _"stolen, revoked or invalid certificates"_:

https://github.com/ditekshen/detection/blob/76863acf1564ed697a2e1eba803908c27e98cdc7/yara/indicator_knownbad_certs.yar#L7141-L7153

Can you please indicate how you came to that conclusion?

My credentials reside on a single password protected YubiKey, that I have here with me, and therefore I find it hard to believe that they could be reported as stolen (and I have certainly not had any reports of any issue with those credentials, which I would expect that anybody who presented such an issue to you would also have had the decency to present to me as the owner). And Windows does not report the certificate as revoked or invalid when running a digitally signed application.

So I would really like to know how you came to classify my certificate as _"stolen, revoked or invalid"_.

If there is information that you feel should not be shared publicly about this, you can also reach me at: support@akeo.ie

**Comment by pbatard** [comment]
For reference, your rule is currently being reported by VirusTotal in:
https://www.virustotal.com/gui/file/6d362897059df29d9674112a43e68dbc549ba4c25e7036dd9fae7c92bfafda02/detection

**Comment by pbatard** [comment]
Also for reference, commit 503298a24e76b2421655a04968954c4e8e30e457 appears to be the one where this change was introduced.

**Comment by ditekshen** [comment]
This was based on https://www.virustotal.com/gui/file/c7faae85681abe125b9a81b798daf845c62ddab8014784b6fd1b184b02d5a22b/detection

Fixed in https://github.com/ditekshen/detection/commit/f3e3ad2dd32f2a6bf9acc8b98a7aa5b08f28be15

**Comment by pbatard** [comment]
Thanks. From what I can see at https://www.virustotal.com/gui/file/c7faae85681abe125b9a81b798daf845c62ddab8014784b6fd1b184b02d5a22b/details, whoever created the malware may have attempted to stick our signature data to their payload, so you might end up with our signature, but also a very explicit `The digital signature of the object did not verify`, which is expected in this case.

I would therefore encourage you to only flag certificates that you have evidence were used in a signed payload that does pass signature validation, otherwise people are going to start affixing existing signature data to malicious payloads just so that competitor software gets flagged by your rules...

**Comment by HenkPoley** [comment]
A similar thing is seen here for the Google (Chrome) updater: https://www.virustotal.com/gui/file/a913415626433d5d0f07d3ec4084a67ff6f5138c3c3f64e36dd0c1ae4c423c65/detection

INDICATOR_KB_CERT_0c15be4a15bb0903c901b1d6c265302f
and
INDICATOR_KB_CERT_06aea76bac46a9e8cfe6d29e45aaf033
