### ISSUE TITLE
False positive on WinRAR setup?

### ISSUE THREAD

**Issue by casperklein** [ditekshen/detection#7]
File: https://www.rarlab.com/rar/winrar-x64-611d.exe

VirusTotal: https://www.virustotal.com/gui/file/ebcb635257c85bb64d06aca82a2e6f51d0f4b968128822bb5a79275e40dce1a5/detection/f-ebcb635257c85bb64d06aca82a2e6f51d0f4b968128822bb5a79275e40dce1a5-1646871217

>Matches rule INDICATOR_KB_CERT_731d40ae3f3a1fb2bc3d8395 by ditekSHen from ruleset indicator_knownbad_certs at https://github.com/ditekshen/detection
Detects executables signed with stolen, revoked or invalid certificate

**Comment by ditekshen** [comment]
Thank you. This was fixed.
