### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by krypt0x** [ditekshen/detection#9]
Hi there, some AV software using your ruleset is wrongly reporting our wallet as a Trojan/Virus. 

Could you please assist?

https://github.com/ConcealNetwork/conceal-desktop

https://www.virustotal.com/gui/file/65aa9266c675e9e9ed55d4eb315a7a27804c24329c6ed7c908c504403317b12d

Thank you

**Comment by krypt0x** [comment]
Would you be kind enough to whitelist us?

![image](https://user-images.githubusercontent.com/35565671/170460510-bbb23b8c-aae1-4371-8f04-6f0d09f0be64.png)

**Comment by ditekshen** [comment]
I cannot be responsible of how "AV software" use the rules. Can you specify which rule is causing the false positive? Can you provide a file or hash to test with?

**Comment by krypt0x** [comment]
`Crowdsourced YARA rules
Matches rule INDICATOR_SUSPICIOUS_EXE_RawGitHub_URL by ditekSHen from ruleset indicator_suspicious at https://github.com/ditekshen/detection
Detects executables containing URLs to raw contents of a Github gist`

https://www.virustotal.com/gui/file/65aa9266c675e9e9ed55d4eb315a7a27804c24329c6ed7c908c504403317b12d/details

**Comment by krypt0x** [comment]
![image](https://github.com/ditekshen/detection/assets/35565671/21251739-e8c0-4490-8c34-79aa74416b3e)

**Comment by krypt0x** [comment]
Crowdsourced YARA rules
Matches rule INDICATOR_SUSPICIOUS_EXE_RawGitHub_URL by ditekSHen from ruleset indicator_suspicious at https://github.com/ditekshen/detection
Detects executables containing URLs to raw contents of a Github gist
Matches rule MacOS_Cryptominer_Generic_333129b7 by Elastic Security from ruleset MacOS_Cryptominer_Generic at https://github.com/elastic/protections-artifacts
Matches rule skip20_sqllang_hook by Mathieu Tartare <mathieu.tartare@eset.com> from ruleset skip20_sqllang_hook at https://github.com/eset/malware-ioc
YARA rule to detect if a sqllang.dll version is targeted by skip-2.0. Each byte pattern corresponds to a function hooked by skip-2.0. If $1_0 or $1_1 match, it is probably targeted as it corresponds to the hook responsible for bypassing the authentication.

**Comment by krypt0x** [comment]
![image](https://github.com/ditekshen/detection/assets/35565671/03aa91e4-171d-4147-a223-11913ef48dca)

**Comment by krypt0x** [comment]
> I cannot be responsible of how "AV software" use the rules. Can you specify which rule is causing the false positive? Can you provide a file or hash to test with?

I got it now. Thanks
